all: check extract

check:
		@echo "\n";
		@echo "--------------";
		@echo "Check norm";
		@norminette -R CheckForbiddenSourceHeader ft*.c;
		@echo "--------------";

extract:
		@echo "\n";
		@echo "--------------";
		@echo "Extract test case by mr card"
		@tar -xvf test*.tar


